import assert from 'node:assert/strict';import fs from 'node:fs';import {spawn,execFileSync} from 'node:child_process';import {syncBuiltinESMExports} from 'node:module';
process.env.JOY_REVIEW_SRC='/tmp/joy-test-tmux/review3/wave3a-followup-astra-checkout/packages/joy-daemon/src';
const {opencode,root,dir}=await import('./wave2d-astra-helpers.mts');
let accepted=false,interrupts=0,release!:(v:any)=>void;const oc=opencode();
oc.__setup({prompt:()=>new Promise(r=>release=(v:any)=>{accepted=true;r(v)}),interrupt:async()=>{interrupts++}});
const outer=oc.enqueue('/joy-prompt',{source:'rpc',mirrorToRelay:false});assert.ok(outer.reinjectionId);const plucked=oc.cancelQueued(outer.reinjectionId);assert.equal(plucked,true);release({messageID:outer.reinjectionId});await new Promise(r=>setTimeout(r,20));assert.equal(accepted,true);assert.equal(interrupts,0);console.log('BUG in-flight OpenCode reinjection: cancelQueued true, later HTTP admission, zero interrupt; lane skips abort for true');
const {killOpencodeServerPid}=await import(root+'/opencode/opencodeClient.ts');
const p=spawn('python3',['-u','-c','import signal,time,os\nsignal.signal(signal.SIGTERM,lambda *_:None)\nprint(os.getpid(),flush=True)\nwhile True:time.sleep(1)'],{detached:true,stdio:['ignore','pipe','pipe']});await new Promise(r=>p.stdout.once('data',r));
const read=fs.readFileSync,readdir=fs.readdirSync;
try{fs.readFileSync=((path:any,...args:any[])=>{if(String(path).startsWith('/proc/'))throw new Error('proc unavailable');return (read as any)(path,...args)}) as any;fs.readdirSync=((path:any,...args:any[])=>{if(String(path)==='/proc')throw new Error('proc unavailable');return (readdir as any)(path,...args)}) as any;syncBuiltinESMExports();const gone=await killOpencodeServerPid(p.pid!);assert.equal(gone,true);assert.equal(process.kill(p.pid!,0),true);console.log('REGRESSION no /proc: TERM-ignoring live process is declared gone immediately');}finally{fs.readFileSync=read;fs.readdirSync=readdir;syncBuiltinESMExports();try{process.kill(-p.pid!,'SIGKILL')}catch{}}
const repo=dir+'/sha256';fs.mkdirSync(repo);execFileSync('git',['init','-q','--object-format=sha256'],{cwd:repo});fs.writeFileSync(repo+'/first.txt','first');execFileSync('git',['add','.'],{cwd:repo});assert.throws(()=>execFileSync('git',['diff','4b825dc642cb6eb9a060e54bf8d69288fbee4904','--','.'],{cwd:repo,stdio:'pipe'}),/bad (object|revision)/);console.log('Residual unborn SHA-256 repository: hardcoded SHA-1 empty tree fails');process.exit(0);
