/**
 * English translations for the Joy app
 * Values can be:
 * - String constants for static text
 * - Functions with typed object parameters for dynamic text
 */

/**
 * English plural helper function
 * @param options - Object containing count, singular, and plural forms
 * @returns The appropriate form based on count
 */
function plural({ count, singular, plural }: { count: number; singular: string; plural: string }): string {
    return count === 1 ? singular : plural;
}

export const en = {
    tabs: {
        // Tab navigation labels
        sessions: 'Terminals',
        settings: 'Settings',
    },

    common: {
        // Simple string constants
        cancel: 'Cancel',
        stop: 'Stop',
        tapAgainToConfirm: ({ label }: { label: string }) => `Tap again: ${label}`,
        authenticate: 'Authenticate',
        save: 'Save',
        saveAs: 'Save As',
        error: 'Error',
        success: 'Success',
        ok: 'OK',
        continue: 'Continue',
        back: 'Back',
        create: 'Create',
        rename: 'Rename',
        reset: 'Reset',
        logout: 'Logout',
        yes: 'Yes',
        no: 'No',
        discard: 'Discard',
        version: 'Version',
        copied: 'Copied',
        share: 'Share',
        copy: 'Copy',
        scanning: 'Scanning...',
        urlPlaceholder: 'https://example.com',
        home: 'Home',
        message: 'Message',
        files: 'Files',
        fileViewer: 'File Viewer',
        loading: 'Loading...',
        retry: 'Retry',
        delete: 'Delete',
        optional: 'optional',
        edit: 'Edit',
    },

    profile: {
        userProfile: 'User Profile',
        details: 'Details',
        firstName: 'First Name',
        lastName: 'Last Name',
        username: 'Username',
        status: 'Status',
    },

    status: {
        connected: 'connected',
        machinesConnected: ({ online, total }: { online: number; total: number }) => `${online}/${total} connected`,
        connecting: 'connecting',
        disconnected: 'disconnected',
        error: 'error',
        online: 'online',
        offline: 'offline',
        lastSeen: ({ time }: { time: string }) => `last seen ${time}`,
        permissionRequired: 'permission required',
        detached: 'detached',
        compacting: 'compacting',
        tasksCompleted: ({ done, total }: { done: number; total: number }) => `${done}/${total} tasks`,
        agentsRunning: ({ done, total }: { done: number; total: number }) => `${done}/${total} agents`,
        retrying: ({ attempt, total }: { attempt: number; total: number }) => `retrying ${attempt}/${total}`,
        activeNow: 'Active now',
        unknown: 'unknown',
        unread: 'new results',
        backgroundProcesses: ({ count }: { count: number }) => count === 1 ? '1 process' : `${count} processes`,
    },

    time: {
        justNow: 'just now',
        minutesAgo: ({ count }: { count: number }) => `${count} minute${count !== 1 ? 's' : ''} ago`,
        hoursAgo: ({ count }: { count: number }) => `${count} hour${count !== 1 ? 's' : ''} ago`,
        daysAgo: ({ count }: { count: number }) => `${count} day${count !== 1 ? 's' : ''} ago`,
    },

    connect: {
        restoreAccount: 'Restore Account',
        enterSecretKey: 'Please enter a secret key',
        invalidSecretKey: 'Invalid secret key. Please check and try again.',
        enterUrlManually: 'Enter URL manually',
    },

    settings: {
        title: 'Settings',
        connectedAccounts: 'Connected Accounts',
        connectAccount: 'Connect account',
        github: 'GitHub',
        machines: 'Machines',
        showOfflineMachines: ({ count }: { count: number }) => count === 1 ? 'Show 1 offline machine' : `Show ${count} offline machines`,
        hideOfflineMachines: 'Hide offline machines',
        features: 'Features',
        account: 'Account',
        accountSubtitle: 'Manage your account details',
        appearance: 'Appearance',
        appearanceSubtitle: 'Customize how the app looks',
        voice: 'Voice',
        voiceSubtitle: 'Talk to your sessions through your ElevenLabs agent',
        mods: 'Mods',
        modsSubtitle: 'Toggle app modifications',
        voiceAssistant: 'Voice Assistant',
        voiceAssistantSubtitle: 'Configure voice interaction preferences',
        featuresTitle: 'Features',
        featuresSubtitle: 'Enable or disable app features',
        developer: 'Developer',
        developerTools: 'Developer Tools',
        about: 'About',
        aboutFooter: 'Joy is a Codex and Claude Code mobile client. It\'s fully end-to-end encrypted and your account is stored only on your device. Not affiliated with Anthropic.',
        whatsNew: 'What\'s New',
        whatsNewSubtitle: 'See the latest updates and improvements',
        reportIssue: 'Report an Issue',
        privacyPolicy: 'Privacy Policy',
        termsOfService: 'Terms of Service',
        supportUs: 'Support us',
        supportUsSubtitlePro: 'Thank you for your support!',
        supportUsSubtitle: 'Support project development',
        scanQrCodeToAuthenticate: 'Scan QR code to authenticate',
        githubConnected: ({ login }: { login: string }) => `Connected as @${login}`,
        connectGithubAccount: 'Connect your GitHub account',
        claudeAuthSuccess: 'Successfully connected to Claude',
        exchangingTokens: 'Exchanging tokens...',
        usage: 'Usage',
        usageSubtitle: 'View your API usage and costs',
        appLock: 'App Lock',
        appLockSubtitle: 'Require Face ID or device PIN to open the app',
        sessions: 'Sessions',
        sessionsSubtitle: 'Manage tmux-based sessions',
        debug: 'Debug',
        joyHttp: 'Joy HTTP',
        joyHttpSubtitle: 'Direct HTTP access to joy-tmux server',
        // Dynamic settings messages
        accountConnected: ({ service }: { service: string }) => `${service} account connected`,
        machineStatus: ({ name, status }: { name: string; status: 'online' | 'offline' }) =>
            `${name} is ${status}`,
        featureToggled: ({ feature, enabled }: { feature: string; enabled: boolean }) =>
            `${feature} ${enabled ? 'enabled' : 'disabled'}`,
    },

    settingsAppearance: {
        // Appearance settings screen
        theme: 'Theme',
        themeDescription: 'Choose your preferred color scheme',
        themeOptions: {
            adaptive: 'Adaptive',
            light: 'Light', 
            dark: 'Dark',
        },
        themeDescriptions: {
            adaptive: 'Match system settings',
            light: 'Always use light theme',
            dark: 'Always use dark theme',
        },
        display: 'Display',
        displayDescription: 'Control layout and spacing',
        inlineToolCalls: 'Inline Tool Calls',
        inlineToolCallsDescription: 'Display tool calls directly in chat messages',
        expandTodoLists: 'Expand Todo Lists',
        expandTodoListsDescription: 'Show all todos instead of just changes',
        showLineNumbersInDiffs: 'Show Line Numbers in Diffs',
        showLineNumbersInDiffsDescription: 'Display line numbers in code diffs',
        showLineNumbersInToolViews: 'Show Line Numbers in Tool Views',
        showLineNumbersInToolViewsDescription: 'Display line numbers in tool view diffs',
        wrapLinesInDiffs: 'Wrap Lines in Diffs',
        wrapLinesInDiffsDescription: 'Wrap long lines instead of horizontal scrolling in diff views',
        diffStyle: 'Diff View',
        diffStyleDescription: 'Show diffs as a single column (unified) or side-by-side (split). Split view is web-only.',
        diffStyleOptions: {
            unified: 'Unified',
            split: 'Split',
        },
        alwaysShowContextSize: 'Always Show Context Size',
        alwaysShowContextSizeDescription: 'Display context usage even when not near limit',
        avatarStyle: 'Avatar Style',
        avatarStyleDescription: 'Choose session avatar appearance',
        avatarOptions: {
            pixelated: 'Pixelated',
            gradient: 'Gradient',
            brutalist: 'Brutalist',
        },
        showFlavorIcons: 'Show AI Provider Icons',
        showFlavorIconsDescription: 'Display AI provider icons on session avatars',
        chatFontSize: 'Chat Font Size',
        chatFontSizeDescription: 'Make message text in chats larger or smaller',
        chatFontSizeIncrease: 'Increase chat font size',
        chatFontSizeDecrease: 'Decrease chat font size',
        chatFontSizePreviewUser: 'How do I resize text?',
        chatFontSizePreviewAgent: 'Like this — adjust with the + and − buttons.',
    },

    settingsSessions: {
        machines: 'Machines',
        machine: 'Machine',
        machineFooter: 'Machine running joy-tmux',
        noMachine: 'No machines connected',
        selectMachine: 'Select Machine',
        statusOnline: 'online',
        statusOffline: 'offline',
        showOfflineMachines: ({ count }: { count: number }) => `Show ${count} offline ${count === 1 ? 'machine' : 'machines'}`,
        hideOfflineMachines: 'Hide offline machines',
        serverUrl: 'Server URL',
        serverUrlFooter: 'URL of the joy-tmux server running on your machine',
        sessions: 'Sessions',
        noSessions: 'No active sessions',
        loading: 'Loading...',
        newSession: 'New Session',
        workingDirectory: 'Working Directory',
        workingDirectoryPlaceholder: 'e.g. /home/user/projects',
        confirmKill: 'Kill Session',
        confirmKillMessage: 'This will terminate the Claude process and cannot be undone.',
        killSession: 'Kill',
        screenshot: 'Screenshot',
        viewPane: 'View Pane',
        statusStarting: 'Starting',
        statusActive: 'Active',
        statusEnded: 'Ended',
    },

    settingsUpdates: {
        jsUpdate: 'JS Update',
        jsUpdateDescription: 'Which JavaScript bundle is running (changes on OTA updates)',
        checkForUpdate: 'Check for updates',
        upToDate: 'Already on the latest version',
        updating: 'Update downloaded — restarting…',
    },

    settingsFeatures: {
        // Features settings screen
        experiments: 'Experiments',
        experimentsDescription: 'Enable experimental features that are still in development. These features may be unstable or change without notice.',
        experimentalFeatures: 'Experimental Features',
        experimentalFeaturesEnabled: 'Experimental features enabled',
        experimentalFeaturesDisabled: 'Using stable features only',
        webFeatures: 'Web Features',
        webFeaturesDescription: 'Features available only in the web version of the app.',
        enterToSend: 'Enter to Send',
        enterToSendEnabled: 'Press Enter to send (Shift+Enter for a new line)',
        enterToSendDisabled: 'Enter inserts a new line',
        commandPalette: 'Command Palette',
        commandPaletteEnabled: 'Press ⌘K to open',
        commandPaletteDisabled: 'Quick command access disabled',
        markdownCopyV2: 'Markdown Copy v2',
        markdownCopyV2Subtitle: 'Long press opens copy modal',
        hideInactiveSessions: 'Hide inactive sessions',
        hideInactiveSessionsSubtitle: 'Show only active chats in your list',
        groupToolCalls: 'Group Tool Calls',
        groupToolCallsSubtitle: 'Collapse consecutive tool calls into one container',
        privacy: 'Privacy',
        privacyDescription: 'Completely disables all analytics and telemetry. No data will be sent to PostHog or any other tracking service.',
        disableAnalytics: 'Disable Analytics',
        analyticsDisabled: 'All tracking and telemetry disabled',
        analyticsEnabled: 'Anonymous usage analytics active',
        limitSessionMemory: 'Limit session memory',
        limitSessionMemorySubtitle: 'Max recent sessions kept in memory; older ones unload + reload on revisit',
        limitSessionMemoryMessage: 'Max recent sessions to keep in memory. Empty = keep all.',
        limitSessionMemoryPlaceholder: 'e.g. 5',
        limitSessionMemoryAll: 'All',
    },

    imageUpload: {
        attachTitle: 'Attach',
        photoLibrary: 'Photo Library',
        chooseFile: 'Choose File',
        pasteImage: 'Paste Image',
        draw: 'Draw',
        pasteNoImageTitle: 'No Image',
        pasteNoImageMessage: 'The clipboard does not contain an image.',
        limitTitle: 'Image Limit Reached',
        limitMessage: ({ max }: { max: number }) => `You can attach up to ${max} images per message.`,
        fileTooLargeTitle: 'File Too Large',
        fileTooLargeMessage: ({ name, maxMb }: { name: string; maxMb: number }) => `"${name}" exceeds the ${maxMb}MB limit and was not added.`,
        emptyFileMessage: ({ name }: { name: string }) => `"${name}" is empty and was not sent.`,
        uploadFailedTitle: 'Upload Failed',
        uploadFailedMessage: ({ count }: { count: number }) => count === 1
            ? 'The attachment could not be uploaded. The message was not sent.'
            : `${count} attachments could not be uploaded. The message was not sent.`,
    },

    errors: {
        sendFailedTitle: 'Message Not Sent',
        sendFailedMessage: 'Your message could not be sent. It has been put back in the composer so you can try again.',
        networkError: 'Network error occurred',
        serverError: 'Server error occurred',
        unknownError: 'An unknown error occurred',
        connectionTimeout: 'Connection timed out',
        authenticationFailed: 'Authentication failed',
        permissionDenied: 'Permission denied',
        fileNotFound: 'File not found',
        invalidFormat: 'Invalid format',
        operationFailed: 'Operation failed',
        tryAgain: 'Please try again',
        contactSupport: 'Contact support if the problem persists',
        sessionNotFound: 'Session not found',
        voiceSessionFailed: 'Failed to start voice session',
        voiceServiceUnavailable: 'Voice service is temporarily unavailable',
        voiceLimitReachedTitle: 'Voice Limit Reached',
        voiceHardLimitReached: ({ hours }: { hours: number }) => `You've used ${hours}+ hours of voice this month. This is the maximum allowed. You can configure your own ElevenLabs agent in Voice settings to use your own quota.`,
        oauthInitializationFailed: 'Failed to initialize OAuth flow',
        tokenStorageFailed: 'Failed to store authentication tokens',
        oauthStateMismatch: 'Security validation failed. Please try again',
        tokenExchangeFailed: 'Failed to exchange authorization code',
        oauthAuthorizationDenied: 'Authorization was denied',
        webViewLoadFailed: 'Failed to load authentication page',
        failedToLoadProfile: 'Failed to load user profile',
        userNotFound: 'User not found',
        sessionDeleted: 'Session has been deleted',
        sessionDeletedDescription: 'This session has been permanently removed',

        // Error functions with context
        fieldError: ({ field, reason }: { field: string; reason: string }) =>
            `${field}: ${reason}`,
        validationError: ({ field, min, max }: { field: string; min: number; max: number }) =>
            `${field} must be between ${min} and ${max}`,
        retryIn: ({ seconds }: { seconds: number }) =>
            `Retry in ${seconds} ${seconds === 1 ? 'second' : 'seconds'}`,
        errorWithCode: ({ message, code }: { message: string; code: number | string }) =>
            `${message} (Error ${code})`,
        disconnectServiceFailed: ({ service }: { service: string }) => 
            `Failed to disconnect ${service}`,
        connectServiceFailed: ({ service }: { service: string }) =>
            `Failed to connect ${service}. Please try again.`,
        failedToLoadFriends: 'Failed to load friends list',
        failedToAcceptRequest: 'Failed to accept friend request',
        failedToRejectRequest: 'Failed to reject friend request',
        failedToRemoveFriend: 'Failed to remove friend',
        searchFailed: 'Search failed. Please try again.',
        failedToSendRequest: 'Failed to send friend request',
    },

    newSession: {
        title: 'Start New Session',
        machineOffline: 'Machine is offline',
        switchMachinesHint: '• Switch machines by clicking on the machine above',
    },

    sessionHistory: {
        // Used by session history screen
        title: 'Session History',
        empty: 'No sessions found',
        today: 'Today',
        yesterday: 'Yesterday',
        daysAgo: ({ count }: { count: number }) => `${count} ${count === 1 ? 'day' : 'days'} ago`,
        viewAll: 'View all sessions',
    },

    session: {
        messageFrom: ({ from }: { from: string }) => `from ${from}`,
        inputPlaceholder: 'Type a message ...',
        inactiveArchived: 'This session is inactive.',
        resumeFromTerminal: 'To resume it from the terminal:',
        newChat: 'New chat',
        // Fork / duplicate / rewind flow (Claude only)
        forkAction: 'Fork session',
        forkSubtitle: 'Continue in a new session with the same context',
        duplicateAction: 'Duplicate from message…',
        duplicateSubtitle: 'Rewind to a chosen point and try again',
        forkFromHere: 'Fork from here',
        duplicateSheetTitle: 'Choose a rewind point',
        duplicateSheetSubtitle: 'The new session keeps the chosen turn complete (your message and the agent’s response) and drops every prompt after it.',
        duplicateSheetConfirm: 'Duplicate',
        duplicateSheetEmpty: 'No messages eligible for rewind in this session yet.',
        duplicateRowDisabled: "This message can't be used as a rewind point.",
        forkedFromLabel: 'Forked from',
        forkedFromSubtitle: 'Open the session this fork was branched from',
        forkErrorOffline: 'This machine is offline. Fork is only available while the machine that owns the session is online.',
        forkErrorMissingUuid: 'The chosen rewind point is no longer present in the source session — try forking without truncation.',
        forkErrorMissingMetadata: 'Missing session metadata required to fork.',
        forkErrorGeneric: 'Failed to fork the session.',
        forkClaudeOnly: 'Fork is currently only supported for Claude sessions.',
    },

    goal: {
        // GoalBar — the pinned /goal bar at the top of the chat
        label: 'GOAL',
        editTitle: 'Edit goal',
        editMessage: 'Set a new goal for the agent. Empty to keep the current one.',
    },

    codexApproval: {
        label: 'APPROVAL',
        allow: 'Allow',
        deny: 'Deny',
    },
    joyDialog: {
        label: 'ACTION NEEDED',
        fallbackTitle: 'Claude Code is asking a question',
        openTerminal: 'Open the terminal to answer',
    },
    joyLogin: {
        // LoginBar — pinned sign-in bar for interactive CLI logins
        label: 'SIGN IN',
        urlCopied: 'Login URL copied to clipboard',
        copyUrl: 'Copy login URL',
        openUrl: 'Open login URL',
        codePlaceholder: 'Paste code here…',
        submitCode: 'Submit login code',
    },

    joyLogs: {
        resumeThisSession: 'Resume this session…',
    },
    joyQueue: {
        header: ({ count }: { count: number }) => count === 1 ? '1 queued' : `${count} queued`,
        // Queued-message strip above the composer (JoyQueueStrip)
        pausedInputDirty: 'The session’s input box has stray text — tap to clear and resume',
        pausedDispatchMismatch: 'A send may not have gone through cleanly — tap to resume',
        pausedDefault: 'A queued message didn’t send — tap to resume',
        queuedMessage: 'Queued message',
        pendingItem: ({ text }: { text: string }) => `queued: ${text}`,
        pendingCount: ({ count }: { count: number }) => count === 1 ? '1 message queued…' : `${count} messages queued…`,
        editTitle: 'Edit queued message',
        hintWeb: 'right-click a message to edit or delete',
        hintTouch: 'hold a message to edit or delete',
        // App-side pending queue (PendingQueueStrip) + offline banner.
        pendingHeader: ({ count }: { count: number }) => count === 1 ? '1 waiting to send' : `${count} waiting to send`,
        waitingForNetwork: 'Waiting for connection…',
        sendFailedOffline: 'Couldn’t send — no connection',
        retry: 'Retry',
        sendRetrying: ({ reason }: { reason: string }) => `Couldn’t send — ${reason}. Trying again…`,
        sendParked: ({ reason }: { reason: string }) => `Couldn’t send — ${reason}. Tap ↻ to try again.`,
        draftsTitle: 'Drafts',
        pendingTitle: 'Waiting to send',
        draftPlaceholder: 'Draft…',
        sendNow: 'Send',
        expand: 'Expand',
        collapse: 'Collapse',
        moreItems: ({ count }: { count: number }) => `+${count} more`,
        offlineBanner: 'No connection — queued messages will send when you’re back online',
    },

    // Per-message delivery status under a sent user message (iMessage-style).

    commandPalette: {
        placeholder: 'Type a command or search...',
    },

    server: {
        // Used by Server Configuration screen (app/(app)/server.tsx)
        serverConfiguration: 'Server Configuration',
        knownRelays: 'Known relays',
        relayLogin: 'Log in to relay',
        relayLoginMessage: 'No account is saved for this relay on this device. Use your current secret key here, enter a different one, or log in later.',
        relayUseCurrentKey: 'Use my current key',
        relayEnterKey: 'Enter secret key',
        relayLoginLater: 'Log in later',
        relayLoginFailed: 'Could not log in to this relay. Check the key and try again.',
        relayApplyKeyAll: 'Use this key on all relays',
        relayAccessKeyLabel: 'Relay access key',
        relayAccessKeyFooter: 'Perimeter key for this relay (joy-relay gate). Sent with every request; leave empty for open relays. Reconnects after saving.',
        relayAccessKeySaved: 'Relay key saved',
        relayCopyDerivedKey: 'Copy derived relay key',
        relayApplyKeyAllMessage: 'Log in to every known relay with the current account key? This replaces any other account saved for those relays on this device.',
        relayApplyKeyAllFooter: 'Makes your current secret key the single login for every known relay — one code to back up. Accounts are created automatically on relays where none exist yet.',
        relayApplyKeyAllSuccess: 'All relays now use this key.',
        relayApplyKeyAllPartial: 'Could not set up:',
        enterServerUrl: 'Please enter a server URL',
        notValidJoyServer: 'Not a valid Joy Server',
        changeServer: 'Change Server',
        continueWithServer: 'Continue with this server?',
        resetToDefault: 'Reset to Default',
        resetServerDefault: 'Reset server to default?',
        validating: 'Validating...',
        validatingServer: 'Validating server...',
        serverReturnedError: 'Server returned an error',
        failedToConnectToServer: 'Failed to connect to server',
        currentlyUsingCustomServer: 'Currently using custom server',
        customServerUrlLabel: 'Custom Server URL',
        advancedFeatureFooter: "This is an advanced feature. Only change the server if you know what you're doing. You will need to log out and log in again after changing servers."
    },

    sessionInfo: {
        // Used by Session Info screen (app/(app)/session/[id]/info.tsx)
        killSession: 'Kill Session',
        killSessionConfirm: 'Are you sure you want to terminate this session?',
        archiveSession: 'Archive Session',
        archiveSessionConfirm: 'Are you sure you want to archive this session?',
        failedToCopySessionId: 'Failed to copy Joy Session ID',
        claudeCodeSessionId: 'Claude Code Session ID',
        claudeCodeSessionIdCopied: 'Claude Code Session ID copied to clipboard',
        codexThreadId: 'Codex Thread ID',
        codexThreadIdCopied: 'Codex Thread ID copied to clipboard',
        aiProvider: 'AI Provider',
        failedToCopyClaudeCodeSessionId: 'Failed to copy Claude Code Session ID',
        failedToCopyCodexThreadId: 'Failed to copy Codex Thread ID',
        metadataCopied: 'Session metadata copied to clipboard',
        failedToCopyMetadata: 'Failed to copy session metadata',
        failedToKillSession: 'Failed to kill session',
        failedToArchiveSession: 'Failed to archive session',
        connectionStatus: 'Connection Status',
        created: 'Created',
        lastUpdated: 'Last Updated',
        sequence: 'Sequence',
        quickActions: 'Quick Actions',
        viewMachine: 'View Machine',
        viewMachineSubtitle: 'View machine details and sessions',
        resumeSession: 'Resume Session',
        resumeSessionSubtitle: 'Resume this session on the same machine',
        resumeSessionSameMachineOnly: 'This session can only be resumed on the same machine it started on.',
        resumeSessionMachineOffline: 'This machine is offline. Resume is only available while it is online.',
        resumeSessionMissingMachine: 'This session is missing its machine metadata, so it cannot be resumed.',
        resumeSessionMissingBackendId: 'This session does not have a resumable Claude or Codex identifier.',
        resumeSessionUnexpectedDirectoryPrompt: 'Resume cannot create directories. Start the session manually from its original path.',
        killSessionSubtitle: 'Immediately terminate the session',
        archiveSessionSubtitle: 'Archive this session and stop it',
        resetChatState: 'Reset chat state',
        resetChatStateSubtitle: 'Clear this chat\'s local data and re-download it',
        resetChatStateWarning: 'Clears this session\'s locally cached messages and re-downloads the conversation from the server. Nothing on the server or the machine is touched. Use when the chat looks frozen or behind.',
        metadata: 'Metadata',
        host: 'Host',
        path: 'Path',
        operatingSystem: 'Operating System',
        processId: 'Process ID',
        copyMetadata: 'Copy session metadata',
        agentState: 'Agent State',
        controlledByUser: 'Controlled by User',
        pendingRequests: 'Pending Requests',
        activity: 'Activity',
        thinking: 'Thinking',
        thinkingSince: 'Thinking Since',
        cliVersion: 'CLI Version',
        cliVersionOutdated: 'CLI Update Required',
        cliVersionOutdatedMessage: ({ currentVersion, requiredVersion }: { currentVersion: string; requiredVersion: string }) =>
            `Version ${currentVersion} installed. Update to ${requiredVersion} or later`,
        deleteSession: 'Delete Session',
        deleteSessionSubtitle: 'Permanently remove this session',
        deleteSessionConfirm: 'Delete Session Permanently?',
        deleteSessionWarning: 'This action cannot be undone. All messages and data associated with this session will be permanently deleted.',
        failedToDeleteSession: 'Failed to delete session',
        sessionDeleted: 'Session deleted successfully',
        worktreeCleanupTitle: 'Delete Worktree?',
        worktreeCleanupMessage: 'The worktree has no uncommitted changes. Would you like to delete the worktree files?',
        worktreeCleanupDelete: 'Delete Worktree',
        worktreeCleanupKeep: 'Keep Files',
        
    },

    components: {
        emptyMainScreen: {
            // Used by EmptyMainScreen component
            readyToCode: 'Ready to code?',
            installCli: 'Install the Joy CLI',
            runIt: 'Run it',
            scanQrCode: 'Scan the QR code',
            openCamera: 'Open Camera',
        },
    },

    agentInput: {
        permissionMode: {
            title: 'PERMISSION MODE',
            default: 'default permissions',
            acceptEdits: 'accept edits',
            plan: 'plan',
            dontAsk: "don't ask",
            bypassPermissions: 'yolo',
            badgeAcceptAllEdits: 'accept all edits',
            badgeBypassAllPermissions: 'yolo',
            badgePlanMode: 'plan mode',
        },
        agent: {
            claude: 'Claude',
            codex: 'Codex',
            gemini: 'Gemini',
            openclaw: 'OpenClaw',
            opencode: 'OpenCode',
        },
        model: {
            title: 'MODEL',
            configureInCli: 'Configure models in CLI settings',
        },
        effort: {
            title: 'EFFORT',
        },
        codexPermissionMode: {
            title: 'CODEX PERMISSION MODE',
            default: 'default permissions',
            readOnly: 'read-only',
            safeYolo: 'safe yolo',
            yolo: 'yolo',
            badgeReadOnly: 'read-only',
            badgeSafeYolo: 'safe yolo',
            badgeYolo: 'yolo',
        },
        codexModel: {
            title: 'CODEX MODEL',
            gpt5CodexLow: 'gpt-5-codex low',
            gpt5CodexMedium: 'gpt-5-codex medium',
            gpt5CodexHigh: 'gpt-5-codex high',
            gpt5Minimal: 'GPT-5 Minimal',
            gpt5Low: 'GPT-5 Low',
            gpt5Medium: 'GPT-5 Medium',
            gpt5High: 'GPT-5 High',
        },
        geminiPermissionMode: {
            title: 'GEMINI PERMISSION MODE',
            default: 'default permissions',
            autoEdit: 'auto edit',
            yolo: 'yolo',
            plan: 'plan',
            badgeAutoEdit: 'auto edit',
            badgeYolo: 'yolo',
            badgePlan: 'plan',
        },
        context: {
            remaining: ({ percent }: { percent: number }) => `${percent}% left`,
        },
        suggestion: {
            fileLabel: 'FILE',
            folderLabel: 'FOLDER',
        },
        noMachinesAvailable: 'No machines',
    },

    machineLauncher: {
        showLess: 'Show less',
        showAll: ({ count }: { count: number }) => `Show all (${count} paths)`,
        enterCustomPath: 'Enter custom path',
        offlineUnableToSpawn: 'Unable to spawn new session, offline',
    },

    sidebar: {
        sessionsTitle: 'Joy',
        showArchived: 'Show archived',
        hideArchived: 'Hide archived',
        newSession: 'New session',
    },

    zen: {
        toggle: 'Zen mode',
    },

    appLock: {
        prompt: 'Unlock joy',
        unlock: 'Unlock',
        noAuthTitle: 'No device security',
        noAuth: 'Set up Face ID or a device passcode first — the lock uses them.',
    },

    toolView: {
        input: 'Input',
        output: 'Output',
        openFile: 'Open file',
        diff: 'Diff',
    },

    toolGroup: {
        editedFile: 'Edited file',
        workedFor: ({ duration }: { duration: string }) => `Worked ${duration}`,
        editedFiles: ({ count }: { count: number }) => count === 1 ? 'Edited 1 file' : `Edited ${count} files`,
        readFiles: ({ count }: { count: number }) => count === 1 ? 'Read 1 file' : `Read ${count} files`,
        ranCommands: ({ count }: { count: number }) => count === 1 ? 'Ran 1 command' : `Ran ${count} commands`,
        searched: ({ count }: { count: number }) => count === 1 ? 'Searched 1 time' : `Searched ${count} times`,
        fetchedUrls: ({ count }: { count: number }) => count === 1 ? 'Fetched 1 URL' : `Fetched ${count} URLs`,
        ranTasks: ({ count }: { count: number }) => count === 1 ? 'Ran 1 task' : `Ran ${count} tasks`,
        usedTools: ({ count }: { count: number }) => count === 1 ? 'Used 1 tool' : `Used ${count} tools`,
    },

    tools: {
        fullView: {
            description: 'Description',
            inputParams: 'Input Parameters',
            output: 'Output',
            error: 'Error',
            completed: 'Tool completed successfully',
            noOutput: 'No output was produced',
            running: 'Tool is running...',
            rawJsonDevMode: 'Raw JSON (Dev Mode)',
        },
        taskView: {
            initializing: 'Initializing agent...',
            moreTools: ({ count }: { count: number }) => `+${count} more ${plural({ count, singular: 'tool', plural: 'tools' })}`,
        },
        multiEdit: {
            editNumber: ({ index, total }: { index: number; total: number }) => `Edit ${index} of ${total}`,
            replaceAll: 'Replace All',
        },
        names: {
            task: 'Task',
            terminal: 'Terminal',
            searchFiles: 'Search Files',
            search: 'Search',
            searchContent: 'Search Content',
            listFiles: 'List Files',
            planProposal: 'Plan proposal',
            readFile: 'Read File',
            editFile: 'Edit File',
            writeFile: 'Write File',
            fetchUrl: 'Fetch URL',
            readNotebook: 'Read Notebook',
            editNotebook: 'Edit Notebook',
            todoList: 'Todo List',
            webSearch: 'Web Search',
            reasoning: 'Reasoning',
            applyChanges: 'Update file',
            viewDiff: 'Current file changes',
            question: 'Question',
        },
        askUserQuestion: {
            submit: 'Submit Answer',
            tapAgain: 'Tap again to submit',
            multipleQuestions: ({ count }: { count: number }) => `${count} questions`,
            other: 'Other',
            otherDescription: 'Type your own answer',
            otherPlaceholder: 'Type your answer...',
        },
        desc: {
            terminalCmd: ({ cmd }: { cmd: string }) => `Terminal(cmd: ${cmd})`,
            searchPattern: ({ pattern }: { pattern: string }) => `Search(pattern: ${pattern})`,
            searchPath: ({ basename }: { basename: string }) => `Search(path: ${basename})`,
            fetchUrlHost: ({ host }: { host: string }) => `Fetch URL(url: ${host})`,
            editNotebookMode: ({ path, mode }: { path: string; mode: string }) => `Edit Notebook(file: ${path}, mode: ${mode})`,
            todoListCount: ({ count }: { count: number }) => `Todo List(count: ${count})`,
            webSearchQuery: ({ query }: { query: string }) => `Web Search(query: ${query})`,
            grepPattern: ({ pattern }: { pattern: string }) => `grep(pattern: ${pattern})`,
            multiEditEdits: ({ path, count }: { path: string; count: number }) => `${path} (${count} edits)`,
            readingFile: ({ file }: { file: string }) => `Reading ${file}`,
            writingFile: ({ file }: { file: string }) => `Writing ${file}`,
            modifyingFile: ({ file }: { file: string }) => `Modifying ${file}`,
            modifyingFiles: ({ count }: { count: number }) => `Modifying ${count} files`,
            modifyingMultipleFiles: ({ file, count }: { file: string; count: number }) => `${file} and ${count} more`,
            showingDiff: 'Showing changes',
        }
    },

    files: {
        changes: 'Changes',
        searchPlaceholder: 'Search files...',
        detachedHead: 'detached HEAD',
        summary: ({ staged, unstaged }: { staged: number; unstaged: number }) => `${staged} staged • ${unstaged} unstaged`,
        notRepo: 'Not a git repository',
        notUnderGit: 'This directory is not under git version control',
        searching: 'Searching files...',
        noFilesFound: 'No files found',
        noFilesInProject: 'No files in project',
        tryDifferentTerm: 'Try a different search term',
        searchResults: ({ count }: { count: number }) => `Search Results (${count})`,
        projectRoot: 'Project root',
        stagedChanges: ({ count }: { count: number }) => `Staged Changes (${count})`,
        unstagedChanges: ({ count }: { count: number }) => `Unstaged Changes (${count})`,
        // File viewer strings
        loadingFile: ({ fileName }: { fileName: string }) => `Loading ${fileName}...`,
        binaryFile: 'Binary File',
        cannotDisplayBinary: 'Cannot display binary file content',
        diff: 'Diff',
        source: 'Source',
        rendered: 'Rendered',
        file: 'File',
        fileEmpty: 'File is empty',
        noChanges: 'No changes to display',
        binaryNoDiff: 'Binary file — no preview',
        noChangesTitle: 'No changes',
        noChangesSubtitle: 'Working tree is clean',
        deleted: 'Deleted',
        changedFiles: ({ count }: { count: number }) => `${count} changed ${count === 1 ? 'file' : 'files'}`,
        allFiles: 'All Files',
        collapseAll: 'Collapse all',
        editFile: 'Edit',
        saveFile: 'Save',
        failedToRead: 'Failed to read file',
        failedToSave: 'Failed to save file',
        fileConflict: 'File conflict',
        fileConflictDescription: 'This file was modified on the device while you were editing. Reload to see the latest version.',
        reload: 'Reload',
        overwrite: 'Overwrite',
    },


    settingsAccount: {
        // Account settings screen
        accountInformation: 'Account Information',
        status: 'Status',
        statusActive: 'Active',
        statusNotAuthenticated: 'Not Authenticated',
        anonymousId: 'Anonymous ID',
        publicId: 'Public ID',
        notAvailable: 'Not available',
        linkNewDevice: 'Link New Device',
        linkNewDeviceSubtitle: 'Scan QR code to link device',
        profile: 'Profile',
        name: 'Name',
        github: 'GitHub',
        tapToDisconnect: 'Tap to disconnect',
        server: 'Server',
        backup: 'Backup',
        backupDescription: 'Your secret key is the only way to recover your account. Save it in a secure place like a password manager.',
        secretKey: 'Secret Key',
        tapToReveal: 'Tap to reveal',
        tapToHide: 'Tap to hide',
        secretKeyLabel: 'SECRET KEY (TAP TO COPY)',
        secretKeyCopied: 'Secret key copied to clipboard. Store it in a safe place!',
        secretKeyCopyFailed: 'Failed to copy secret key',
        privacy: 'Privacy',
        privacyDescription: 'Help improve the app by sharing anonymous usage data. No personal information is collected.',
        analytics: 'Analytics',
        analyticsDisabled: 'No data is shared',
        analyticsEnabled: 'Anonymous usage data is shared',
        dangerZone: 'Danger Zone',
        logout: 'Logout',
        logoutSubtitle: 'Sign out and clear local data',
        logoutConfirm: 'Are you sure you want to logout? Make sure you have backed up your secret key!',
    },

    settingsLanguage: {
        // Language settings screen
        title: 'Language',
        description: 'Choose your preferred language for the app interface. This will sync across all your devices.',
        currentLanguage: 'Current Language',
        automatic: 'Automatic',
        automaticSubtitle: 'Detect from device settings',
        needsRestart: 'Language Changed',
        needsRestartMessage: 'The app needs to restart to apply the new language setting.',
        restartNow: 'Restart Now',
    },

    connectButton: {
        authenticate: 'Authenticate Terminal',
        authenticateWithUrlPaste: 'Authenticate Terminal with URL paste',
        pasteAuthUrl: 'Paste the auth URL from your terminal',
    },

    updateBanner: {
        updateAvailable: 'Update available',
        pressToApply: 'Press to apply the update',
        whatsNew: "What's new",
        seeLatest: 'See the latest updates and improvements',
        nativeUpdateAvailable: 'App Update Available',
        tapToUpdateAppStore: 'Tap to update in App Store',
        tapToUpdatePlayStore: 'Tap to update in Play Store',
    },

    changelog: {
        // Used by the changelog screen
        version: ({ version }: { version: number }) => `Version ${version}`,
        noEntriesAvailable: 'No changelog entries available.',
    },

    terminal: {
        // Used by terminal connection screens
        webBrowserRequired: 'Web Browser Required',
        webBrowserRequiredDescription: 'Terminal connection links can only be opened in a web browser for security reasons. Please use the QR code scanner or open this link on a computer.',
        processingConnection: 'Processing connection...',
        invalidConnectionLink: 'Invalid Connection Link',
        invalidConnectionLinkDescription: 'The connection link is missing or invalid. Please check the URL and try again.',
        connectTerminal: 'Connect Terminal',
        terminalRequestDescription: 'A terminal is requesting to connect to your Joy account. This will allow the terminal to send and receive messages securely.',
        connectionDetails: 'Connection Details',
        publicKey: 'Public Key',
        encryption: 'Encryption',
        endToEndEncrypted: 'End-to-end encrypted',
        acceptConnection: 'Accept Connection',
        connecting: 'Connecting...',
        reject: 'Reject',
        security: 'Security',
        securityFooter: 'This connection link was processed securely in your browser and was never sent to any server. Your private data will remain secure and only you can decrypt the messages.',
        securityFooterDevice: 'This connection was processed securely on your device and was never sent to any server. Your private data will remain secure and only you can decrypt the messages.',
        clientSideProcessing: 'Client-Side Processing',
        linkProcessedLocally: 'Link processed locally in browser',
        linkProcessedOnDevice: 'Link processed locally on device',
    },

    modals: {
        // Used across connect flows and settings
        authenticateTerminal: 'Authenticate Terminal',
        pasteUrlFromTerminal: 'Paste the authentication URL from your terminal',
        deviceLinkedSuccessfully: 'Device linked successfully',
        terminalConnectedSuccessfully: 'Terminal connected successfully',
        invalidAuthUrl: 'Invalid authentication URL',
        developerMode: 'Developer Mode',
        developerModeEnabled: 'Developer mode enabled',
        developerModeDisabled: 'Developer mode disabled',
        disconnectGithub: 'Disconnect GitHub',
        disconnectGithubConfirm: 'Are you sure you want to disconnect your GitHub account?',
        disconnectService: ({ service }: { service: string }) => 
            `Disconnect ${service}`,
        disconnectServiceConfirm: ({ service }: { service: string }) => 
            `Are you sure you want to disconnect ${service} from your account?`,
        disconnect: 'Disconnect',
        failedToConnectTerminal: 'Failed to connect terminal',
        cameraPermissionsRequiredToConnectTerminal: 'Camera permissions are required to connect terminal',
        failedToLinkDevice: 'Failed to link device',
        cameraPermissionsRequiredToScanQr: 'Camera permissions are required to scan QR codes'
    },

    navigation: {
        // Navigation titles and screen headers
        connectTerminal: 'Connect Terminal',
        linkNewDevice: 'Link New Device', 
        restoreWithSecretKey: 'Restore with Secret Key',
        whatsNew: "What's New",
    },

    welcome: {
        // Main welcome screen for unauthenticated users
        title: 'Vibe Happily',
        subtitle: 'End-to-end encrypted and your account is stored only on your device.',
        createAccount: 'Create account',
        linkOrRestoreAccount: 'Link or restore account',
        loginWithMobileApp: 'Login',
    },

    review: {
        // Used by utils/requestReview.ts
        enjoyingApp: 'Enjoying the app?',
        feedbackPrompt: "We'd love to hear your feedback!",
        yesILoveIt: 'Yes, I love it!',
        notReally: 'Not really'
    },

    items: {
        // Used by Item component for copy toast
        copiedToClipboard: ({ label }: { label: string }) => `${label} copied to clipboard`
    },

    voice: {
        noAgentTitle: 'No voice agent',
        noAgentMessage: 'Add an ElevenLabs agent under Settings → Voice first.',
        startFailed: ({ reason }: { reason: string }) => `Could not start voice: ${reason}`,
        micTitle: 'Microphone access required',
        micAskAgain: 'Joy needs the microphone for voice. Allow it when asked.',
        micSettings: 'Joy needs the microphone for voice. Enable it in your device settings.',
        micWeb: 'Allow microphone access in your browser: click the lock icon in the address bar and enable the microphone for this site.',
        micOpenSettings: 'Open Settings',
        statusConnecting: 'Connecting…',
        statusLive: 'Voice live',
        statusArmed: 'Joy idle',
        listeningHint: 'Listening · tap to talk',
        statusError: 'Voice error',
        tapToPause: 'Tap to pause',
        tapToTalk: 'Tap to talk',
        end: 'End voice',
    },
    settingsVoice: {
        agentsTitle: 'Agents',
        agentsFooter: 'A public agent needs only its id. A private agent (authentication on) also needs an API key; the key stays in your encrypted settings and is only used to mint conversation tokens.',
        noAgents: 'No agents yet',
        addAgent: 'Add agent',
        addAgentName: 'Name',
        addAgentNamePlaceholder: 'e.g. Joy',
        addAgentId: 'Agent id',
        addAgentIdPlaceholder: 'agent_…',
        addAgentKey: 'API key',
        addAgentKeyMessage: 'Leave empty for a public agent.',
        inUse: 'In use',
        publicAgent: 'Public agent',
        privateAgent: 'Private agent (key set)',
        use: 'Use this agent',
        rename: 'Rename',
        setKey: 'Set API key',
        replaceKey: 'Replace API key',
        remove: 'Remove',
        removeConfirm: ({ name }: { name: string }) => `Remove "${name}"?`,
        behaviorTitle: 'Standing by',
        wakeOnEvents: 'Wake on session events',
        wakeOnEventsSubtitle: 'While standing by, reconnect and speak when a turn ends, an approval is held, or a question is asked.',
        wakeOnSound: 'Wake on sound',
        wakeOnSoundSubtitle: 'While idle and the app is open, listen on the device and reconnect when you start talking. Sound level only, not word recognition: a TV or a nearby conversation can wake it too.',
        idleTimeout: 'Hang up after silence',
        idleTimeoutSubtitle: ({ seconds }: { seconds: number }) => `${seconds === 0 ? 'Never' : `${seconds} seconds`}`,
        idleTimeoutPrompt: 'Seconds of silence before the conversation hangs up and stands by. 0 = never.',
        setupTitle: 'Agent setup',
        setupFooter: 'On the ElevenLabs dashboard the agent needs: overrides enabled for system prompt and first message (Security tab); client tools sendMessageToSession(sessionId, message) and processPermissionRequest(requestId, decision); optionally the built-in skip_turn tool.',
    },
    machine: {
        environment: 'Environment',
        environmentFooter: 'Provider keys (FIREWORKS_API_KEY, …) every new session on this machine inherits. Stored sealed on the machine; values never come back to the app.',
        environmentAdd: 'Add variable',
        environmentAddSubtitle: 'Name, then value — applies to sessions started from now on',
        environmentNamePrompt: 'Variable name',
        environmentValuePrompt: ({ name }: { name: string }) => `Value for ${name}`,
        environmentRemoveTitle: 'Remove variable',
        environmentRemoveMessage: ({ name }: { name: string }) => `Remove ${name} from this machine? Running sessions keep it until they restart.`,
        environmentNone: 'No variables yet',
        environmentUnavailable: 'Pair this machine first (joy auth) to unlock the store',
        launchNewSessionInDirectory: 'Launch New Session in Directory',
        offlineUnableToSpawn: 'Launcher disabled while machine is offline',
        offlineHelp: '• Make sure your computer is online\n• Run `joy status` to diagnose',
        daemon: 'Daemon',
        status: 'Status',
        stopDaemon: 'Stop Daemon',
        lastKnownPid: 'Last Known PID',
        lastKnownHttpPort: 'Last Known HTTP Port',
        startedAt: 'Started At',
        cliVersion: 'CLI Version',
        daemonStateVersion: 'Daemon State Version',
        activeSessions: ({ count }: { count: number }) => `Active Sessions (${count})`,
        machineGroup: 'Machine',
        host: 'Host',
        machineId: 'Machine ID',
        username: 'Username',
        homeDirectory: 'Home Directory',
        platform: 'Platform',
        architecture: 'Architecture',
        lastSeen: 'Last Seen',
        never: 'Never',
        metadataVersion: 'Metadata Version',
        cliAvailability: 'CLI Availability',
        cliInstalled: 'Installed',
        cliNotFound: 'Not found',
        lastDetected: 'Last Detected',
        untitledSession: 'Untitled Session',
        back: 'Back',
        dangerZone: 'Danger Zone',
        delete: 'Delete Machine',
        deleteFooter: 'Remove this machine from your account. Session history will be preserved, but you will not be able to start new sessions on this machine.',
        deleteConfirmTitle: 'Delete this machine?',
        deleteConfirmMessage: 'The machine will be removed from your account. Session history will be preserved, but you will not be able to start new sessions until you reconnect the daemon.',
        deleteFailed: 'Failed to delete machine.',
        system: 'System',
        name: 'Name',
        renameTitle: 'Rename machine',
        renameMessage: ({ host }: { host: string }) => `Custom name for this machine (leave empty to use the hostname "${host}")`,
        systemFooter: 'Live host stats from the daemon heartbeat (~20s).',
        cpuCores: ({ count }: { count: number }) => count === 1 ? '1 core' : `${count} cores`,
        loadAverage: ({ load }: { load: string }) => `load ${load}`,
        memoryUsedPercent: ({ percent }: { percent: number }) => `${percent}% used`,
        diskFree: ({ free, total }: { free: string; total: string }) => `${free} / ${total} free`,
        ramHot: ({ percent }: { percent: number }) => `RAM ${percent}% on this machine`,
        diskHot: ({ percent }: { percent: number }) => `Disk ${percent}% full on this machine`,
    },

    message: {
        switchedToMode: ({ mode }: { mode: string }) => `Switched to ${mode} mode`,
        compactionSummary: 'Compaction summary',
        contextCompacted: 'Context compacted',
        reuse: 'Reuse',
        unknownEvent: 'Unknown event',
        usageLimitUntil: ({ time }: { time: string }) => `Usage limit reached until ${time}`,
        unknownTime: 'unknown time',
    },

    codex: {
        // Codex permission dialog buttons
        permissions: {
            yesForSession: "Yes, and don't ask for a session",
            stopAndExplain: 'Stop, and explain what to do',
        }
    },

    claude: {
        // Claude permission dialog buttons
        permissions: {
            yesAllowAllEdits: 'Yes, allow all edits during this session',
            yesAllowEverything: 'Yes, allow everything during this session',
            yesForTool: "Yes, don't ask again for this tool",
            noTellClaude: 'No, and provide feedback',
        }
    },

    textSelection: {
        // Text selection screen
        selectText: 'Select text range',
        title: 'Select Text',
        noTextProvided: 'No text provided',
        textNotFound: 'Text not found or expired',
        textCopied: 'Text copied to clipboard',
        failedToCopy: 'Failed to copy text to clipboard',
        noTextToCopy: 'No text available to copy',
    },

    markdown: {
        // Markdown copy functionality
        codeCopied: 'Code copied',
        copyFailed: 'Copy failed',
        mermaidRenderFailed: 'Failed to render mermaid diagram',
    },



} as const;

export type Translations = typeof en;

/**
 * Generic translation type that matches the structure of Translations
 * but allows different string values (for other languages)
 */
export type TranslationStructure = {
    readonly [K in keyof Translations]: {
        readonly [P in keyof Translations[K]]: Translations[K][P] extends string 
            ? string 
            : Translations[K][P] extends (...args: any[]) => string 
                ? Translations[K][P] 
                : Translations[K][P] extends object
                    ? {
                        readonly [Q in keyof Translations[K][P]]: Translations[K][P][Q] extends string
                            ? string
                            : Translations[K][P][Q]
                      }
                    : Translations[K][P]
    }
};
